# ==============================================================================
# ParchaOS's icon theme: ParchaOS's own drawings for apps, folders, file types and
# a few symbols, over GNOME's Adwaita (look-alike audit, 2026-10-02). It used to be
# built on a third-party Mac-style icon theme; none of that artwork is installed
# any more. Every other icon falls back to Adwaita and hicolor.
#
# theme-skeleton.tsv (generated once from the earlier theme, keeping only the
# names that answered with ParchaOS's own drawings) says which icon names each
# drawing serves; build-theme.py assembles the theme from it; index-sections.ini
# holds the directory definitions. The three theme names (ParchaOS, -dark, -light)
# are the same set, since the drawings do not change with the colour scheme.
# ==============================================================================

Name:           parchaos-icon-theme
Version:        2026.09.23
Release:        23%{?dist}
Summary:        ParchaOS icon theme (original drawings over Adwaita)

License:        CC-BY-SA-4.0
URL:            https://github.com/Spanglish-Enterprises/parchaos-gnome
Source90:       LICENSE-ARTWORK
# ParchaOS's own app icons: see parchaos-icons/README.md.
Source1:        parcher.svg
Source2:        parcha-store.svg
Source3:        parchaos-web-browser.svg
Source4:        parcha-browser.svg
# Batch 2 (ticket #13): icons for the most visible apps, generated by
# parchaos-icons/generate.py.
Source5:        parchaos-calendar.svg
Source6:        parchaos-clock.svg
Source7:        parchaos-calculator.svg
Source8:        parchaos-contacts.svg
Source9:        parchaos-mail.svg
Source10:        parchaos-settings.svg
Source11:        parchaos-terminal.svg
Source12:        parchaos-text-editor.svg
Source13:        parchaos-weather.svg
Source14:        parchaos-screenshot.svg
Source15:        parchaos-system-monitor.svg
Source16:        parchaos-disks.svg
# Batch 3 (ticket #13): folders and trash (places), generated too.
Source17:       parchaos-folder.svg
Source18:       parchaos-folder-open.svg
Source19:       parchaos-folder-documents.svg
Source20:       parchaos-folder-download.svg
Source21:       parchaos-folder-music.svg
Source22:       parchaos-folder-images.svg
Source23:       parchaos-folder-videos.svg
Source24:       parchaos-folder-desktop.svg
Source25:       parchaos-folder-home.svg
Source26:       parchaos-folder-templates.svg
Source27:       parchaos-folder-public.svg
Source28:       parchaos-folder-remote.svg
Source29:       parchaos-trash.svg
Source30:       parchaos-trash-full.svg
# Batch 4 (ticket #13).
Source31:       parchaos-preview.svg
Source32:       parchaos-archive.svg
Source33:       parchaos-firmware.svg
# The ParchaOS mark (the start-here and launcher-widget names).
Source34:       parchaos-logo.svg
Source35:       parchaos-logo-symbolic.svg
# The keyboard glyph (input-keyboard-symbolic).
Source36:       parchaos-keyboard-symbolic.svg
# ParchaOS's cloud icon.
Source38:       parchaos-cloud.svg
Source40:       parchaos-mime-generic.svg
Source41:       parchaos-mime-text.svg
Source42:       parchaos-mime-code.svg
Source43:       parchaos-mime-document.svg
Source44:       parchaos-mime-spreadsheet.svg
Source45:       parchaos-mime-presentation.svg
Source46:       parchaos-mime-pdf.svg
Source47:       parchaos-mime-image.svg
Source48:       parchaos-mime-audio.svg
Source49:       parchaos-mime-video.svg
Source50:       parchaos-mime-archive.svg
Source51:       parchaos-mime-package.svg
Source52:       parchaos-mime-disk.svg
Source53:       parchaos-mime-font.svg
Source54:       parchaos-mime-certificate.svg
Source55:       parchaos-mime-contact.svg
Source56:       parchaos-mime-calendar.svg
Source57:       parchaos-mime-mail.svg
Source58:       parchaos-mime-web.svg
Source59:       parchaos-mime-database.svg
# The "show apps" glyph (ticket #113): a 3x3 grid of small rounded squares.
Source60:       parchaos-launcher-symbolic.svg
# Folder colour variants (ticket #79): the generator recolours the folders and
# the trash in the build, so the variants are never committed as art.
Source72:       generate.py
# Builds the theme from the drawings (see the header).
Source73:       build-theme.py
Source74:       theme-skeleton.tsv
Source75:       index-sections.ini

BuildArch:      noarch
BuildRequires:  python3

# gtk-update-icon-cache builds the caches for the themes we ship.
BuildRequires:  gtk-update-icon-cache

Requires:       hicolor-icon-theme
# Whatever ParchaOS does not draw falls back to GNOME's icons.
Requires:       adwaita-icon-theme

%description
ParchaOS's icon theme: original ParchaOS drawings for apps, folders and file
types, a few symbols, and the ParchaOS mark. Anything it does not draw falls
back to GNOME's Adwaita icons.

%prep
%setup -q -c -T
cp -p %{SOURCE90} .

%build
# nothing to compile

%install
mkdir -p %{buildroot}%{_datadir}/icons
for theme in ParchaOS ParchaOS-dark ParchaOS-light; do
    python3 %{SOURCE73} %{buildroot}%{_datadir}/icons/$theme $theme %{_sourcedir}
done

# Folder colour variants (ticket #79). Each is a small theme that holds only
# recoloured folders and trash and inherits everything else from the dark or
# light base, so switching colour never changes the rest of the icons.
python3 %{SOURCE72} --variants variants
folder_names="folder folder-open folder-documents folder-download folder-music folder-images folder-videos user-desktop user-home folder-templates folder-public folder-html user-trash user-trash-full"
for pair in folder:parchaos-folder folder-open:parchaos-folder-open folder-documents:parchaos-folder-documents \
            folder-download:parchaos-folder-download folder-music:parchaos-folder-music folder-images:parchaos-folder-images \
            folder-videos:parchaos-folder-videos user-desktop:parchaos-folder-desktop user-home:parchaos-folder-home \
            folder-templates:parchaos-folder-templates folder-public:parchaos-folder-public folder-html:parchaos-folder-remote \
            user-trash:parchaos-trash user-trash-full:parchaos-trash-full; do
    echo "${pair%%%%:*} ${pair#*:}"
done > variants/names.txt
for base in dark light; do
    for pal in berry sunny leaf ocean graphite; do
        Pal=$(echo "${pal:0:1}" | tr a-z A-Z)${pal:1}
        theme=ParchaOS-$base-$Pal
        root=%{buildroot}%{_datadir}/icons/$theme
        d=$root/places/scalable
        mkdir -p "$d"
        while read -r icon file; do
            install -m 0644 "variants/$pal/$file.svg" "$d/$icon.svg"
        done < variants/names.txt
        # Names that are links to one of the folders in the base theme
        # (default-folder, inode-directory, ...) follow the new colour.
        basedir=%{buildroot}%{_datadir}/icons/ParchaOS-$base/places/scalable
        for l in "$basedir"/*.svg; do
            [ -L "$l" ] || continue
            t=$(basename "$(readlink -f "$l")"); n=$(basename "$l")
            case " $folder_names " in
                *" ${t%%%%.svg} "*) [ -e "$d/$n" ] || ln -s "$t" "$d/$n" ;;
            esac
        done
        printf '%%s\n' \
            '[Icon Theme]' \
            "Name=$theme" \
            "Comment=ParchaOS $base icons with $Pal folders" \
            "Inherits=ParchaOS-$base" \
            'Directories=places/scalable' \
            '' \
            '[places/scalable]' \
            'Context=Places' \
            'Size=64' \
            'MinSize=8' \
            'MaxSize=512' \
            'Type=Scalable' > "$root/index.theme"
    done
done

# Build the icon caches for what we ship.
for theme in ParchaOS ParchaOS-dark ParchaOS-light; do
    gtk-update-icon-cache -f -q %{buildroot}%{_datadir}/icons/$theme
done
for theme in %{buildroot}%{_datadir}/icons/ParchaOS-*-*; do
    gtk-update-icon-cache -f -q "$theme"
done

%files
%license LICENSE-ARTWORK
%{_datadir}/icons/*

%changelog
* Fri Oct 02 2026 ParchaOS packaging - 2026.09.23-23
- Look-alike audit: the theme no longer installs any third-party icon artwork. It is built from ParchaOS's own drawings only (build-theme.py, theme-skeleton.tsv, index-sections.ini), over Adwaita and hicolor, so every other icon is GNOME's own. The three theme names (ParchaOS, -dark, -light) hold the same set. The licence is the artwork licence (CC-BY-SA-4.0).

* Fri Oct 02 2026 ParchaOS packaging - 2026.09.23-22
- Look-alike audit: the generic browser icon file is named parchaos-web-browser.svg (the old name was a pun on another company's browser; the drawing is unchanged).

* Wed Sep 30 2026 ParchaOS packaging - 2026.09.23-21
- Ticket #141: a new, soft 3D trash can (empty and full): a rounded
  tapered bin in the folder colour with a grey flanged rim, a hood and a
  swing flap over the opening, and crumpled paper sticking out when full.
* Tue Sep 29 2026 ParchaOS packaging - 2026.09.23-20
- Ticket #79: folder colours. Ten small themes, ParchaOS-dark-<Colour> and
  ParchaOS-light-<Colour> for Berry, Sunny, Leaf, Ocean and Graphite, hold
  recoloured folders and trash and inherit the rest from the dark or light
  base. Generated at build time from generate.py --variants; the default
  (passion) art is unchanged.
* Sun Sep 27 2026 ParchaOS packaging - 2026.09.23-19
- Rename installed icon theme directories from MacTahoe/MacTahoe-dark/
  MacTahoe-light to ParchaOS/ParchaOS-dark/ParchaOS-light (ticket #100).
  Upstream credits and URLs unchanged.
* Sun Sep 27 2026 ParchaOS packaging - 2026.09.23-18
- Original "show apps" glyph (ticket #113): a 3x3 grid of small rounded
  squares, generated by parchaos-icons/generate.py, replacing MacTahoe's
  view-app-grid-symbolic (byte-identical to Adwaita's own dot grid).
  The full-color dock-button treatment (parchaos-gtk-theme's own
  view-app-grid.svg, a near-exact copy of Apple's Launchpad icon) is
  fixed separately, in that package.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-17
- Revised ParchaOS logo: the rind has an open gap and the seeds are
  irregular (no radial symmetry), after a WIPO image search.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-16
- New original ParchaOS logo (halved passion fruit), generated by
  branding/logo/make-brand.py; artwork CC BY-SA 4.0. Replaces the
  adapted third-party icon.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-15
- Keep only ParchaOS's own app icons: every other MacTahoe app icon is
  removed (apps fall back to Adwaita/hicolor), Apple-named files get
  neutral names, and MacTahoe's drawings of Apple hardware and file
  types are removed. The build fails if an excluded name survives.
  Inherits Adwaita,hicolor.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-14
- Stop shipping MacTahoe's cursors (ParchaOS uses Adwaita's); neutral
  summary.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-13
- File-type icons: programs no longer get the spreadsheet icon,
  Makefiles the disk icon, or Word templates the code icon (tighter
  matching, with a self-test).
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-12
- Replace MacTahoe's icloud.svg with ParchaOS's cloud icon.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-11
- Original file-type icons: MacTahoe's page-style file icons (which
  imitate the reference desktop's document icons) are replaced with
  ParchaOS's own, one design per kind of file (text, code, documents,
  spreadsheets, presentations, PDF, images, audio, video, archives,
  packages, disk images, fonts, certificates, contacts, calendars, mail,
  web, databases).
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-10
- Replace MacTahoe's command-key symbol used as the keyboard icon
  (input-keyboard-symbolic) with an original keyboard glyph.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-9
- Replace the Apple-logo start-here, Budgie launcher and folder-apple icons with the ParchaOS mark (a halved passion fruit) and the ParchaOS folder.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-8
- Original icons for the image viewer (Parcha Preview), Archive Manager and
  Firmware; MacTahoe's copied Apple's Preview and Archive Utility, and its
  Firmware icon carried a chip maker's logo (ticket #13).
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-7
- Original ParchaOS folders (violet with a gold tab, with glyphs for
  Documents, Downloads, Music, Pictures, Videos, Desktop, Home, Templates,
  Public and remote folders) and trash (empty/full), replacing MacTahoe's
  Apple-look places icons in all three variants, including their
  fixed-size copies (ticket #13).
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-6
- Original ParchaOS icons for Calendar, Clock, Calculator, Contacts, Mail,
  Settings, Terminal, Text Editor, Weather, Screenshot, System Monitor and
  Disks, replacing MacTahoe's reproductions of Apple's icons (ticket #13).
* Fri Sep 25 2026 ParchaOS packaging - 2026.09.23-5
- Remove MacTahoe's weather condition icons (-large/-small), which
  embed low-resolution raster images and looked pixelated in GNOME
  Weather; the app's own scalable icons from hicolor are used instead.
- Regenerate icon-theme.cache after the spec's icon changes.
* Fri Sep 25 2026 ParchaOS packaging - 2026.09.23-4
- Icon v2: redraw Parcher, Parcha Store and Parcha Browser in the
  MacTahoe palette (folder blues, white tiles, soft violet) so they sit
  naturally in the dock; the v1 gold/magenta palette clashed. Parcher is
  now a white folder on a blue tile (chosen from two drafts).
* Fri Sep 25 2026 ParchaOS packaging - 2026.09.23-3
- Replace MacTahoe's reproductions of Apple's Finder, App Store and
  Safari icons with original ParchaOS artwork for Parcher, Parcha Store,
  Pafari/generic browsers and Parcha Browser (keeps Apple trade dress out
  of the shipped system, per the naming policy).
* Wed Sep 23 2026 ParchaOS packaging - 2026.09.23-2
- Real bug found via a real COPR build attempt: install.sh calls
  gtk-update-icon-cache internally, missing BuildRequires. Icon
  variants themselves installed correctly before this failure.
* Wed Sep 23 2026 ParchaOS packaging - 2026.09.23-1
- Initial package, real upstream source (vinceliuice/MacTahoe-icon-theme,
  GPL-3.0-or-later), pinned to commit 839848b, default color variant.
  Not yet build-tested.
