# ==============================================================================
# ParchaOS's system-logos replacement.
#
# This system runs `generic-logos` (Fedora's own already-de-branded
# fallback for spins/remixes, not the full `fedora-logos` package), which
# is why most of its 86 files never mattered here: Anaconda pixmaps and
# the KDE ksplash/gnome-initial-setup themes only matter to the live-ISO
# installer experience (a separate concern, see engine/), and the boot
# splash and GDM logo are already covered by parchaos-gnome-plymouth-theme
# and parchaos-gdm-logo. What's actually left live and visible on an
# installed system is a handful of icon-name fallbacks some apps still
# reach for by name (`fedora-logo-icon`, `start-here`) plus the legacy
# /usr/share/pixmaps files a few older tools read directly by path.
#
# Reuses the existing parchaos-logo.svg (CC BY-SA 4.0, generated by
# branding/logo/make-brand.py) rather than new artwork -- rasterized to
# the exact pixel sizes generic-logos ships (240x310 portrait canvas for
# fedora-logo.png/system-logo-white.png, 128x128 for fedora-logo-small.png)
# via GdkPixbuf, which already loads this SVG cleanly.
# ==============================================================================

Name:           parchaos-logos
Version:        1.0.0
Release:        1%{?dist}
Summary:        ParchaOS system logos (replaces generic-logos)
License:        CC-BY-SA-4.0
URL:            https://github.com/Spanglish-Enterprises/parchaos-gnome

Source0:        parchaos-logo.svg
Source1:        parchaos-logo.png
Source2:        parchaos-logo-small.png
Source3:        LICENSE-ARTWORK

BuildArch:      noarch

Provides:       system-logos = %{version}-%{release}
Provides:       generic-logos = %{version}-%{release}
Obsoletes:      generic-logos < %{version}-%{release}

%description
Replaces generic-logos' icon-name fallbacks (fedora-logo-icon,
fedora-logo-sprite, start-here) and legacy /usr/share/pixmaps files with
the ParchaOS mark, for the handful that are actually still visible on an
installed system. The live-ISO installer's own Anaconda/firstboot theming
is a separate concern (see engine/); the boot splash and GDM logo are
already covered by parchaos-gnome-plymouth-theme and parchaos-gdm-logo.

%prep
cp -p %{SOURCE3} .

%build

%install
for name in fedora-logo-icon fedora-logo-sprite start-here; do
    install -Dm0644 %{SOURCE0} %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/$name.svg
done
install -Dm0644 %{SOURCE0} %{buildroot}%{_datadir}/icons/hicolor/scalable/places/start-here.svg

install -Dm0644 %{SOURCE0} %{buildroot}%{_datadir}/pixmaps/fedora-logo-sprite.svg
install -Dm0644 %{SOURCE1} %{buildroot}%{_datadir}/pixmaps/fedora-logo.png
install -Dm0644 %{SOURCE1} %{buildroot}%{_datadir}/pixmaps/system-logo-white.png
install -Dm0644 %{SOURCE2} %{buildroot}%{_datadir}/pixmaps/fedora-logo-small.png

%files
%license LICENSE-ARTWORK
%{_datadir}/icons/hicolor/scalable/apps/fedora-logo-icon.svg
%{_datadir}/icons/hicolor/scalable/apps/fedora-logo-sprite.svg
%{_datadir}/icons/hicolor/scalable/apps/start-here.svg
%{_datadir}/icons/hicolor/scalable/places/start-here.svg
%{_datadir}/pixmaps/fedora-logo-sprite.svg
%{_datadir}/pixmaps/fedora-logo.png
%{_datadir}/pixmaps/system-logo-white.png
%{_datadir}/pixmaps/fedora-logo-small.png

%changelog
* Sun Sep 27 2026 ParchaOS packaging - 1.0.0-1
- Initial package (ticket #24): replaces generic-logos' live-visible
  icon-name fallbacks and legacy pixmaps with the ParchaOS mark. Anaconda
  and other live-ISO-only theming from generic-logos is deliberately out
  of scope here -- a separate concern from an already-installed system.
