Name:           parchaos-release
Version:        1.0.0
Release:        7%{?dist}
Summary:        ParchaOS name, logo and links in os-release
License:        GPL-3.0-or-later AND CC-BY-SA-4.0
URL:            https://github.com/Spanglish-Enterprises/parchaos-gnome
Source0:        parchaos-os-release
Source1:        parchaos-logo.svg
Source2:        parchaos-logo-symbolic.svg
Source3:        LICENSE-ARTWORK
# docs/LEGAL.md: licenses, credits, network connections, export notice.
Source4:        LEGAL.md
Source5:        LICENSE
# docs/SOURCES.md: where the source is, and the written offer.
Source6:        SOURCES.md
BuildArch:      noarch

Requires:       generic-release-common
Requires(post): coreutils, grep

%description
Brands the system as ParchaOS in /etc/os-release: name, logo, default
hostname and support links, which GNOME's About page, the boot menu and
other tools show. Version fields stay Fedora's, so dnf and version checks
keep working. Fedora's release package replaces /etc/os-release on every
update, so a trigger writes it again afterwards. Also installs the
ParchaOS logo the os-release LOGO field names.

%prep
cp -p %{SOURCE3} %{SOURCE5} .

%build

%install
install -Dm0644 %{SOURCE4} %{buildroot}%{_datadir}/doc/parchaos/LEGAL.md
install -Dm0644 %{SOURCE6} %{buildroot}%{_datadir}/doc/parchaos/SOURCES.md
install -Dm0755 %{SOURCE0} %{buildroot}%{_libexecdir}/parchaos-os-release
install -Dm0644 %{SOURCE1} %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/parchaos-logo.svg
install -Dm0644 %{SOURCE2} %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps/parchaos-logo-symbolic.svg

%post
%{_libexecdir}/parchaos-os-release || :

%triggerin -- generic-release-common
%{_libexecdir}/parchaos-os-release || :

%postun
# On removal, give /etc/os-release and /etc/system-release back.
if [ "$1" -eq 0 ]; then
    ln -sf ../usr/lib/os-release /etc/os-release || :
    ln -sf ../usr/lib/system-release /etc/system-release || :
fi

%files
%license LICENSE-ARTWORK
%license LICENSE
%dir %{_datadir}/doc/parchaos
%{_datadir}/doc/parchaos/LEGAL.md
%{_datadir}/doc/parchaos/SOURCES.md
%{_libexecdir}/parchaos-os-release
%{_datadir}/icons/hicolor/scalable/apps/parchaos-logo.svg
%{_datadir}/icons/hicolor/symbolic/apps/parchaos-logo-symbolic.svg

%changelog
* Mon Sep 28 2026 ParchaOS packaging - 1.0.0-7
- Ticket #106: Set CPE_NAME to ParchaOS and write /etc/system-release
  to match distribution branding; hook into generic-release-common.
* Sat Sep 26 2026 ParchaOS packaging - 1.0.0-6
- Revised ParchaOS logo: the rind has an open gap and the seeds are
  irregular (no radial symmetry), after a WIPO image search.
* Sat Sep 26 2026 ParchaOS packaging - 1.0.0-5
- New original ParchaOS logo (halved passion fruit), generated by
  branding/logo/make-brand.py; artwork CC BY-SA 4.0. Replaces the
  adapted third-party icon.
* Sat Sep 26 2026 ParchaOS packaging - 1.0.0-4
- Install /usr/share/doc/parchaos/SOURCES.md: where the source is, and
  the written offer.
* Sat Sep 26 2026 ParchaOS packaging - 1.0.0-3
- Install the ParchaOS legal and privacy notice
  (/usr/share/doc/parchaos/LEGAL.md) and the GPL license text.
* Sat Sep 26 2026 ParchaOS packaging - 1.0.0-2
- Ship the logo's CC BY 3.0 attribution (LOGO-CREDITS) as a license
  file.
* Sat Sep 26 2026 ParchaOS packaging - 1.0.0-1
- First release: ParchaOS os-release branding kept across Fedora
  release-package updates, and the ParchaOS logo icon.
