# ==============================================================================
# ParchaOS's GTK/GNOME Shell theme — real Tahoe-styled GTK3/GTK4 theme
# (dock, traffic-light window controls, translucent panels), forked
# from Pulsar OS's own fork
# (Inled-Pulsar-OS/MacTahoe-gtk-theme), which is itself a real fork of
# vinceliuice's well-known MacTahoe-gtk-theme (MIT) — the same trusted
# author whose WhiteSur-kde this project already ported for the KDE
# variant. Confirmed via `gh api` before writing this: Pulsar OS's own
# fork adds no real functional changes over upstream beyond
# accent-color/libadwaita integration tweaks in their own
# prepare-assets.sh; this spec ports directly from the REAL vinceliuice
# upstream instead of going through Pulsar's own fork+patches, since
# their patches are non-essential polish (dynamic accent-color wiring)
# this project can add later once the basic theme is verified working.
#
# License: MIT (matches upstream's own LICENSE/COPYING).
#
# Scoped to a single dark variant for v1 (matching Pulsar OS's own real
# choice: `-c dark`), not the theme's full light/dark x multiple-accent
# matrix — keeps this port narrow and testable rather than trying to
# ship every combination on the first pass.
#
# Uses upstream's own real install.sh (same real mechanism Pulsar OS's
# own packaging uses, confirmed via their prepare-assets.sh) rather
# than hand-copying files, since the script does real SCSS compilation
# (sassc) plus a nontrivial file-selection/renaming pipeline per
# variant that would be error-prone to reimplement by hand. Root/sudo
# checks patched out the same way Pulsar OS's own real prepare-assets.sh
# does it (`UID -ne 0` -> `false`), needed because install.sh normally
# refuses some operations when run as root, but running as root inside
# an RPM %%install/mock chroot is completely normal.
# ==============================================================================

Name:           parchaos-gtk-theme
Version:        2026.09.23
Release:        20%{?dist}
Summary:        ParchaOS GTK3/GTK4 and GNOME Shell theme

License:        MIT AND CC-BY-SA-4.0
URL:            https://github.com/vinceliuice/MacTahoe-gtk-theme
# Pinned to a specific commit for reproducibility (checked via
# `gh api repos/vinceliuice/MacTahoe-gtk-theme/commits/main`, not a
# moving branch reference).
%global commit  09198632e789f72ed46574812ef6d389a53809f0
%global shortcommit %(c=%{commit}; echo ${c:0:7})
Source0:        %{url}/archive/%{commit}/MacTahoe-gtk-theme-%{shortcommit}.tar.gz
# The ParchaOS mark for the shell theme's activities button (upstream
# draws the Apple logo there).
Source1:        parchaos-activities.svg
# view-app-grid.svg (ticket #113): MacTahoe's copy is a near-exact
# reproduction of Apple's own Launchpad icon (rounded square, search
# bar, pastel 2x3 grid) -- painted onto the dock's Show Apps button by
# .show-apps-icon's own background-image, hiding the symbolic icon
# underneath entirely. Generated by parchaos-icons/generate.py.
Source2:        parchaos-launcher.svg
Source91:       LICENSE-ARTWORK

BuildArch:      noarch

BuildRequires:  sassc
BuildRequires:  git
# Real bug found via a real COPR build attempt (2026-09-23, build
# 11024750): install_theme_deps() (libs/lib-install.sh) auto-detects
# missing `glib-compile-resources` (glib2-devel) / `xmllint`
# (libxml2) and, before attempting a `sudo dnf install`, does a real
# internet-connectivity ping (prepare_deps() -> get_utc_epoch_time(),
# opens /dev/tcp/iana.org/80) -- which always fails in COPR's
# network-isolated build sandbox, and even if it somehow succeeded,
# the subsequent unattended `sudo dnf install` would hang forever on
# a password prompt. Our build VM test shell already has both tools
# installed, masking this from every local test until reproduced by
# explicitly hiding them from PATH.
BuildRequires:  glib2-devel
BuildRequires:  libxml2
# Real bug found via a real COPR build attempt (2026-09-23, build
# 11024653): lib-core.sh runs `set -Eeo pipefail` then, near its very
# top (before any output is printed), does
# `SUDO_BIN="$(command -v sudo)"` as a plain assignment -- if `sudo`
# isn't present, that command substitution's nonzero exit kills the
# whole script instantly and silently under errexit. Minimal COPR mock
# chroots don't guarantee `sudo` is present (unlike our own build VM test
# shell, which has it for its own SSH workflow -- that's why local
# testing never reproduced this). `sudo` itself is never actually
# invoked in our root-less RPM build path; it just needs to resolve so
# the assignment succeeds.
BuildRequires:  sudo
# Real bug found at ISO-build time (2026-09-23, not caught by COPR's
# own build since Requires: aren't resolved there): `gnome-themes-extra`
# doesn't exist as an installable package in Fedora 44 at all (`dnf
# repoquery '*gnome-themes*'` returns nothing) -- GNOME bundles Adwaita
# natively now, this package appears retired upstream. Nothing in
# MacTahoe-gtk-theme's own installed files actually needs it (it's a
# GTK3/GTK4 theme, self-contained); dropped rather than guessing at a
# replacement name.
Requires:       gtk-murrine-engine

%description
ParchaOS's GTK3/GTK4 and GNOME Shell theme: translucent panels and
colored window controls. Built with vinceliuice's own install.sh from
MacTahoe-gtk-theme (MIT). Ships both the dark and the light variant.

%prep
%autosetup -n MacTahoe-gtk-theme-%{commit}

# Root/sudo-check patches — same real mechanism Pulsar OS's own
# packaging uses (confirmed against their real prepare-assets.sh)
# because install.sh assumes it's never run as root, but an RPM build
# environment always is. Real bug found via a real COPR build attempt
# (2026-09-23): the first pass here only patched install.sh/tweaks.sh/
# lib-install.sh's UID/EUID checks, but --silent-mode's actual root
# gate lives in a DIFFERENT function (full_sudo(), in libs/lib-core.sh)
# checking `[[ ! -w "/root" ]]` -- a check Pulsar OS's own real
# prepare-assets.sh specifically neutralizes too (confirmed by
# re-reading their script), which this spec's first draft missed.
sed -i 's/UID -ne 0/false/g; s/EUID -ne 0/false/g' install.sh tweaks.sh 2>/dev/null || true
if [ -f libs/lib-core.sh ]; then
    # NOTE (real bug found 2026-09-23, root-caused via BASH_XTRACEFD
    # tracing that survives install.sh's own internal `exec 2>` fd
    # reassignment): a naive `s/! -w "\/root"/false/` here produces
    # `if [[ false ]]; then`, but bash has no boolean literals --
    # `[[ false ]]` is a single-word test, i.e. an implicit `-n false`
    # (is the STRING "false" non-empty?), which is always TRUE. That
    # patch was silently making full_sudo()'s root-check fire
    # unconditionally regardless of actual root status -- the real
    # explanation for why testing as genuine root never helped. Using
    # a real always-false relational test instead.
    sed -i 's/! -w "\/root"/1 -eq 2/g' libs/lib-core.sh
fi
if [ -f libs/lib-install.sh ]; then
    sed -i 's/UID -ne 0/false/g; s/EUID -ne 0/false/g' libs/lib-install.sh
fi
cp -p %{SOURCE91} .

%build
# install.sh does the real work (SCSS compile via sassc, file assembly)
# directly into the destination we pass -- nothing to build separately.

%install
# Real bug found via a real COPR build attempt (2026-09-23, build
# 11024717): install.sh's own -d validation (check_param) requires the
# destination to already exist and be writable -- it doesn't create
# it. Every local verification this session implicitly worked around
# this by mkdir -p'ing the test destination by hand before invoking
# install.sh, masking the fact that the spec itself never did.
# parchaos-icon-theme's spec already does this correctly; this one
# didn't.
mkdir -p %{buildroot}%{_datadir}/themes
./install.sh -c dark -d %{buildroot}%{_datadir}/themes --silent-mode

# Real gap found 2026-09-24 (real user feedback: no light mode; both
# should ship): install.sh's own
# COMMAND_COLOR_VARIANTS (libs/lib-core.sh) is
# ('light' 'dark') -- light was always a real, fully-supported
# upstream variant (a genuine gtk-Light.scss compile path, not a
# reskin of dark), this spec just never built it. The banner comment
# above this %install section even already flagged "dark variant only"
# as a known gap before this. Building it as a second, separate
# install.sh invocation rather than passing both colors to one call:
# install.sh's own default behavior when given multiple -c values is
# to build every combination of ALL variant axes (opacity/theme-accent/
# scheme) for EACH color, multiplying build time and output size far
# beyond what this profile ships (only the default Tahoe-style,
# standard-scheme, normal-opacity combination) -- two separate calls,
# each still implicitly scoped to that one default combination, stay
# fast and produce exactly ParchaOS-Dark and ParchaOS-Light, nothing
# more.
./install.sh -c light -d %{buildroot}%{_datadir}/themes --silent-mode

# Real bug found via log-based live testing 2026-09-25 (real user
# report: the window buttons showed only their icons, without the
# colored circles). Root cause, confirmed against
# upstream's own README ("Fix for libadwaita (not perfect)") and
# libs/lib-install.sh's config_gtk4(): libadwaita apps (most of modern
# GNOME, including Settings/Files) ignore the system theme directory
# entirely for GTK4 CSS -- this theme's *only* way to reach them is a
# separate `-l`/`--libadwaita` install mode that overwrites
# $HOME/.config/gtk-4.0 directly with real colored titlebutton assets
# (confirmed real red/yellow/green circle PNGs in the upstream source
# tree, not a guess). This spec never ran that step, so no account on
# the system -- old or new -- ever got real traffic-light colors in any
# libadwaita app; they silently fell back to stock Adwaita's monochrome
# buttons. config_gtk4()'s TARGET_DIR is a literal "${HOME}/.config/gtk-4.0"
# (not a `-d`-configurable path), so the only way to reach it at package
# build time is to point $HOME itself at a skel-style destination -- the
# same per-user first-login provisioning pattern already used elsewhere
# in this project (systemd user-presets, dconf defaults) for exactly
# this class of "needs to land in a not-yet-created home directory"
# problem. Scoped to dark only for skel, matching this profile's actual
# default color-scheme -- upstream's own docs are explicit that this
# workaround is "not perfect": a libadwaita app can only ever use
# whichever single variant was last installed into gtk-4.0 config, it
# cannot follow the system dark/light toggle. A user who switches to
# light mode would need to manually rerun
# `./install.sh -l -c light` themselves to get matching libadwaita
# colors -- a real, honest upstream limitation, not something this
# package can silently paper over.
mkdir -p %{buildroot}%{_sysconfdir}/skel
HOME=%{buildroot}%{_sysconfdir}/skel ./install.sh -l -c dark --silent-mode
# install.sh also drops a "GNOME-GTK-Theme" switcher app into ~/.local; it
# would show up in every new user's launcher, and ParchaOS sets the theme
# itself, so it isn't shipped.
rm -rf %{buildroot}%{_sysconfdir}/skel/.local

# Ticket #100: same gap as parchaos-icon-theme's spec -- install.sh still
# names what it builds after upstream, so the dirs are MacTahoe-Dark /
# MacTahoe-Light in /usr/share/themes and the same names under
# /etc/skel/.themes. dconf's default (01-parchaos-theme), theme-sync and
# yin-yang's GNOME plugin all ask for ParchaOS-Dark/ParchaOS-Light, so
# without this rename the theme actually shipped is not the theme any of
# them name, and the ticket's "ls shows no MacTahoe*" is unmet. Runs
# after all three install.sh invocations so every copy comes out renamed.
# Only text files are rewritten (grep -I skips binaries), and only the
# ones that can carry a theme name or path -- index.theme and CSS, not
# LICENSE/README, so upstream credits stay intact.
for root in %{buildroot}%{_datadir}/themes %{buildroot}%{_sysconfdir}/skel/.themes; do
    [ -d "$root" ] || continue
    for dir in "$root"/MacTahoe*; do
        [ -e "$dir" ] || continue
        mv "$dir" "$root/ParchaOS${dir##*MacTahoe}"
    done
    find "$root" -type l | while read -r link; do
        target=$(readlink "$link")
        case $target in
            *MacTahoe*)
                ln -sfn "$(printf '%s' "$target" | sed 's/MacTahoe/ParchaOS/g')" "$link"
                ;;
        esac
    done
    grep -rIl MacTahoe "$root" 2>/dev/null | while read -r f; do
        case $f in
            *.css|*.ini|*/index.theme|*/gtkrc) sed -i 's/MacTahoe/ParchaOS/g' "$f" ;;
        esac
    done
done

# config_gtk4() creates gtk.css/gtk-dark.css as symlinks built from the
# literal $HOME we passed above -- since that $HOME IS the buildroot
# path, the symlinks point INTO the buildroot itself
# (.../BUILDROOT/etc/skel/...), which rpmbuild correctly refuses to
# package ("Symlink points to BuildRoot"). Both link targets live in
# the exact same directory as the link itself, so a plain
# basename-only relative symlink is the correct, portable fix -- no
# different behavior once actually installed, just no baked-in
# buildroot path.
GTK4_SKEL=%{buildroot}%{_sysconfdir}/skel/.config/gtk-4.0
ln -sf gtk-Dark.css "$GTK4_SKEL/gtk.css"
ln -sf gtk-Dark.css "$GTK4_SKEL/gtk-dark.css"

# Replace the Apple-logo activities button in every shell theme variant
# (system-wide and the per-user copies in /etc/skel).
find %{buildroot}%{_datadir}/themes %{buildroot}%{_sysconfdir}/skel -path '*/gnome-shell/assets/*' \
    \( -name 'activities.svg' -o -name 'activities-white.svg' \) |
while read -r f; do
    install -m 0644 %{SOURCE1} "$f"
done

# Same fix for the dock's Show Apps button (ticket #113): .show-apps-icon
# paints this file over the symbolic icon entirely via background-image,
# so MacTahoe's near-exact copy of Apple's Launchpad icon was fully
# visible regardless of which icon name the dock set.
find %{buildroot}%{_datadir}/themes %{buildroot}%{_sysconfdir}/skel -path '*/gnome-shell/assets/*' \
    -name 'view-app-grid.svg' |
while read -r f; do
    install -m 0644 %{SOURCE2} "$f"
done

%files
%license LICENSE-ARTWORK
%license COPYING
%doc README.md
%{_datadir}/themes/*
%{_sysconfdir}/skel/.config/gtk-4.0/
# install.sh -l's main() doesn't scope itself to just the gtk-4.0
# config -- it also runs the plain per-user GTK3 install (duplicate
# .themes/ParchaOS-Dark* variants) and installs the bundled
# "gnome-theme-switcher" helper app, all under the same $HOME we
# pointed at skel. Found via a real COPR build failure ("Installed
# but unpackaged"), not guessed. Harmless/expected content for a
# per-user skel (a real theme-switcher app and standard ~/.themes
# entries are normal desktop-Linux conventions), so packaged as-is
# rather than fighting upstream's own bundling.
%{_sysconfdir}/skel/.themes/

%changelog
* Mon Sep 28 2026 ParchaOS packaging - 2026.09.23-20
- Rewrote %description to be user-facing and neutral (ticket
  #105): dropped internal build-diligence notes and lineage
  wording toward other distributions. Upstream project credit
  (authors, licenses) is kept.
* Sun Sep 27 2026 ParchaOS packaging - 2026.09.23-19
- Rename installed theme directories from MacTahoe-Dark/MacTahoe-Light
  to ParchaOS-Dark/ParchaOS-Light (ticket #100). Upstream credits and
  URLs unchanged.
* Sun Sep 27 2026 ParchaOS packaging - 2026.09.23-18
- Real finding (ticket #113): .show-apps-icon's background-image was
  painting MacTahoe's view-app-grid.svg -- a near-exact copy of Apple's
  Launchpad icon (rounded square, search bar, pastel 2x3 grid) -- over
  the dock's Show Apps button, completely hiding the underlying
  symbolic icon regardless of which icon name the dock set. Replaced
  with an original glyph (no search bar, ParchaOS's own palette),
  generated by parchaos-icons/generate.py. The plain symbolic icon
  MacTahoe also ships for this button is fixed separately, in
  parchaos-icon-theme (it was just Adwaita's own dot grid, not an Apple
  copy).
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-17
- Don't ship the upstream theme switcher app in /etc/skel/.local; it
  showed up in every new user's launcher.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-16
- Revised ParchaOS logo: the rind has an open gap and the seeds are
  irregular (no radial symmetry), after a WIPO image search.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-15
- New original ParchaOS logo (halved passion fruit), generated by
  branding/logo/make-brand.py; artwork CC BY-SA 4.0. Replaces the
  adapted third-party icon.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-14
- Neutral summary and description.
* Sat Sep 26 2026 ParchaOS packaging - 2026.09.23-13
- Replace the Apple-logo activities button in every shell theme variant with the ParchaOS mark.
* Fri Sep 25 2026 ParchaOS packaging - 2026.09.23-12
- Reworded comments and changelog to describe user-reported issues
  instead of quoting them.
* Fri Sep 25 2026 ParchaOS packaging - 2026.09.23-11
- Release 10's COPR build failed with "Installed (but unpackaged)
  file(s)": install.sh -l's main() also installs the plain per-user
  GTK3 theme (.themes/ParchaOS-Dark* variants) and the bundled
  gnome-theme-switcher app into the same $HOME, not just the gtk-4.0
  libadwaita config. Added %files entries for %{_sysconfdir}/skel/.themes/
  and %{_sysconfdir}/skel/.local/ rather than fighting upstream's
  bundling -- both are normal, harmless per-user skel content.
* Fri Sep 25 2026 ParchaOS packaging - 2026.09.23-10
- Release 9's COPR build failed: config_gtk4()'s gtk.css/gtk-dark.css
  symlinks are built from the literal $HOME we point at the buildroot,
  so they pointed into the buildroot itself ("Symlink points to
  BuildRoot"). Fixed by recreating both as plain relative (basename-
  only) symlinks after install.sh runs -- same real files, no baked-in
  build-time path. Same libadwaita fix as 106-9 in intent, this is the
  version that actually builds.
* Fri Sep 25 2026 ParchaOS packaging - 2026.09.23-9
- Fixed a real bug found via log-based live testing: traffic-light
  window buttons showed as monochrome icons, not macOS-style colored
  circles, in every libadwaita (GTK4) app. Root cause: this theme's
  colored button assets only reach libadwaita apps via a separate
  `-l`/`--libadwaita` install step that overwrites $HOME/.config/gtk-4.0
  directly -- never run by this spec. Added a skel-targeted invocation
  (HOME=%{buildroot}%{_sysconfdir}/skel) so new accounts get it
  automatically; existing accounts need a one-time manual copy (see
  the project's development notes). Dark-only, matching this profile's
  default -- upstream's own docs note this workaround can't follow the
  system light/dark toggle.
* Thu Sep 24 2026 ParchaOS packaging - 2026.09.23-8
- Real user feedback: no light mode was ever shipped. Confirmed
  upstream's own libs/lib-core.sh has always supported a real 'light'
  color variant (COMMAND_COLOR_VARIANTS=('light' 'dark')) -- this spec
  only ever built 'dark'. Added a second install.sh -c light
  invocation; %files' existing %{_datadir}/themes/* wildcard already
  picks up the new ParchaOS-Light output with no further changes
  needed.
* Wed Sep 23 2026 ParchaOS packaging - 2026.09.23-7
- Real fifth root cause found -- this time not from a COPR build (which
  doesn't resolve Requires:), but from the ISO build's own package
  install: "nothing provides gnome-themes-extra needed by
  parchaos-gtk-theme". Confirmed via `dnf repoquery` that this package
  doesn't exist in Fedora 44 at all (retired upstream, GNOME bundles
  Adwaita natively now). Nothing in the theme's own installed files
  needs it; dropped the Requires rather than guessing a replacement.
* Wed Sep 23 2026 ParchaOS packaging - 2026.09.23-6
- Real fourth root cause found via the actual COPR build log
  (11024750 failed with "DEPS ERROR: You have an internet connection
  issue"): install_theme_deps() auto-detects missing
  glib-compile-resources/xmllint and, before auto-installing them,
  does a real internet-connectivity ping that always fails in COPR's
  network-isolated sandbox (and would otherwise hang on an unattended
  sudo password prompt). the build VM's test shell already had both tools,
  masking this locally. Reproduced by hiding them from PATH; fixed
  with BuildRequires: glib2-devel, libxml2.
* Wed Sep 23 2026 ParchaOS packaging - 2026.09.23-5
- Real third root cause found via the actual COPR build log (11024717
  failed with "'-d' ERROR: You have no permission to access that
  directory."): install.sh's check_param validates `-d` via
  `[[ ! -w "${value}" && ! -w "$(dirname ${value})" ]]` -- a
  nonexistent dest is fine as long as its PARENT exists and is
  writable (it auto-mkdir's just the leaf). But rpmbuild only creates
  the bare %{buildroot} itself, not %{buildroot}%{_datadir}/themes's
  intermediate usr/share/ parents, so BOTH checks failed. Every local
  verification this session used `mkdir -p` on a destination whose
  parent already existed (e.g. /tmp/...), masking this. Reproduced
  exactly with a deeply-nested nonexistent path (parent also missing);
  fixed by mkdir -p'ing the full destination before invoking
  install.sh, matching what parchaos-icon-theme's spec already does.
* Wed Sep 23 2026 ParchaOS packaging - 2026.09.23-4
- Real second root cause found via the actual COPR build log (11024653
  failed with zero install.sh output before "Bad exit status"):
  lib-core.sh's `SUDO_BIN="$(command -v sudo)"` runs under
  `set -Eeo pipefail` near the very top of the script, before any
  output is printed -- if `sudo` isn't present, that assignment's
  nonzero exit kills the whole script instantly and silently. Minimal
  COPR mock chroots don't guarantee `sudo`, unlike our own build VM test
  shell (which has it for SSH workflow use, hiding this locally).
  Reproduced exactly (zero output, exit 1) by stripping sudo from
  PATH; fixed by adding `BuildRequires: sudo` so the assignment
  resolves. sudo itself is never actually invoked in this root-less
  RPM build path.
* Wed Sep 23 2026 ParchaOS packaging - 2026.09.23-3
- REAL ROOT CAUSE FOUND (via BASH_XTRACEFD tracing that survives
  install.sh's own internal `exec 2> error_log.txt` fd reassignment,
  which was hiding the real trace from earlier bash -x attempts): the
  -2 patch's `s/! -w "\/root"/false/` produced `if [[ false ]]; then`,
  but bash has no boolean literals -- `[[ false ]]` is a single-word
  test (implicit `-n false`, is the STRING "false" non-empty?), which
  is always TRUE. That patch made full_sudo()'s check fire
  unconditionally, explaining why testing as genuine verified root
  never helped. Fixed with a real always-false relational test
  (`1 -eq 2`). Verified clean (exit 0) locally as a normal non-root
  user: produces real ParchaOS-Dark / ParchaOS-Dark-solid (+ hdpi/xhdpi
  density variants) directories.
* Wed Sep 23 2026 ParchaOS packaging - 2026.09.23-2
- Real bug found via a real COPR build attempt: --silent-mode's actual
  root check lives in libs/lib-core.sh's full_sudo() (`[[ ! -w "/root"
  ]]`), a different file/check than the UID/EUID patches already
  applied elsewhere -- fixed, matching a check Pulsar OS's own real
  packaging script specifically neutralizes too.
* Wed Sep 23 2026 ParchaOS packaging - 2026.09.23-1
- Initial package, real upstream source (vinceliuice/MacTahoe-gtk-theme,
  MIT), dark variant only. Not yet build-tested -- the install.sh
  invocation and root-check patches are based on Pulsar OS's own real
  prepare-assets.sh usage, but this project's own build environment
  (mock/COPR chroot, not their exact debootstrap/pacstrap setup) hasn't
  been verified to behave identically. Expect real iteration.
